[workspace]
authors = ["Ondřej Čertík <ondrej@certik.us>"]
channels = ["https://prefix.dev/sdl", "conda-forge"]
name = "SDL_gpu_examples"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
build = "rm -rf build && mkdir build && cd build && cmake -G Ninja .. && ninja"

[dependencies]
sdl3 = ">=3.2.26,<4"
ninja = ">=1.13.1,<2"
cmake = ">=4.1.2,<5"
